# Site settings
title: Everpay
email: hello@everpayinc.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "http://everpay.github.io/" # the base hostname & protocol for your site - used for feed.xml
include: ["_pages"]
permalink: /:title/
twitter_username: everpay
github_username:  everpay

# Build settings
markdown: kramdown
